### PR TITLE
changing condition to show .div-animation

### PR DESCRIPTION
**Pull request by sanket143**
Script was taking time until the previous event escapes the screen to load the next event.

### CODE REVIEW

**Comment by KhushilMistry** [comment]
Thanks for your interest in this repo. :)
You can do something like this as another developer will be able to understand it easily.
You can also increase the animation time 2000 milliseconds so that it can notify it on scrolling. 
```
var top_of_object = $(this).position().top;
var bottom_of_window = $(window).scrollTop() + $(window).height();
  
 if (bottom_of_window > top_of_object) {
      $(this).animate({ 'opacity': '1' }, 1500);
}
```

**Comment by sanket143** [comment]
Thank you
I want to make this site fluent since it is so slow on moz, maybe because
it has so many scripts running on it.

Is there any way that can be done ??

Thanks :)

**Comment by KhushilMistry** [comment]
It is due to large images loading on a single page. You can do it by reducing the size each images. Currently index page is loading about 5-10 Mb data which is quite significant. 

Any browser can run way more than scripts which are currently running on the single page.

**Comment by KhushilMistry** [comment]
Hey, I have changed these things 3-4 days ago in last commit.
There is a bug. Parallax effect is not working on Mozila for all starting Fonts like connect,event and gallery.
Can you look into this ?

**Comment by sanket143** [comment]
Sure ... My pleasure

Thanks

**Pull request closed without merging**
